apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: charge-system-http
  namespace: peaner-web
spec:
  selector:
    matchLabels:
      app: charge-system
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: charge-system
    spec:
      volumes:
      - name: peaner-shared-data
        emptyDir: {}
      containers:
        - name: charge-system
          image: 镜像域名/命名空间/charge-system:v1.0.1-dev001
          imagePullPolicy: Always
          env:
          - name: JVM_MAX_MEMORY
            value: "2G"
          - name: SPRING_PROFILE
            value: "dev"
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
          volumeMounts:
          - name: peaner-shared-data
            mountPath: /var/peaner/logs
      imagePullSecrets:
        - name: secret-peaner-web
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: charge-system
  name: charge-system-http
  namespace: peaner-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 18668
    nodePort: 30199
  selector:
    app: charge-system
  type: NodePort
